name: MyApp
options:
  defaultConfig: "Release"
  deploymentTarget:
    iOS: "17.2" # TODO: Find some way to detect the current default deployment target from the user's current Xcode version
settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    GCC_C_LANGUAGE_STANDARD: "gnu17"
    LOCALIZATION_PREFERS_STRING_CATALOGS: "YES"
  configs:
    release:
      VALIDATE_PRODUCT: "YES"
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - MyApp
    # TODO: Test example where Info.plist file is generated
    # Have Xcodegen create an Info.plist file on the filesystem
    # info:
    #   path: MyApp/Info.plist
    #   properties:
    #     # Match Xcode defaults
    #     CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
    #     CFBundleShortVersionString: "$(MARKETING_VERSION)"
    #     CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
    #     LSRequiresIPhoneOS: "YES"
    #     UIApplicationSupportsIndirectInputEvents: "YES"
    settings:
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
        CODE_SIGN_IDENTITY: "Apple Development"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_ASSET_PATHS: "\"MyApp/Preview Content\""
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "YES" # Lets Xcode automatically manage the Info.plist file as part of the project settings
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationPortraitUpsideDown"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: "com.example.MyApp"
        SWIFT_EMIT_LOC_STRINGS: "YES"
