name: MyApp
options:
  defaultConfig: "Release"
  deploymentTarget:
    iOS: "17.2"
settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    GCC_C_LANGUAGE_STANDARD: "gnu17"
    LOCALIZATION_PREFERS_STRING_CATALOGS: "YES"
  configs:
    release:
      VALIDATE_PRODUCT: "YES"
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - MyApp
